version: 2

jobs:
    test:
        docker:
          - image: harisekhon/jython
        steps:
          - checkout
          - run:
              name: Install Dependencies
              command: pip install -r requirements.txt
          - run:
              name: Install MongoDB
              command: apt-get install mongodb -y
          - run:
              name: Run tests
              command: nose tests

    deploy:
        machine:
          enabled: true
        steps:
          - run:
              name: Deploy to squawkapi.chaz.pro
              command: |
                ssh $SSH_USER@$SSH_HOST "~/deploy/dirdapi.sh"


workflows:
  version: 2
  build_and_test:
    jobs:
    - test

